# .streamlit/secrets.toml

OPENAI_API_KEY="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"